### ISSUE TITLE
heif-convert: error: Input file '*.heic' does not exist

### ISSUE THREAD

**Issue by peekaa** [NeverMendel/heif-convert#24]
In windows 10, with python 3.12 converting is not working. 

```
pip install heif-convert
....
heif-convert *.heic -f jpg
heif-convert: error: Input file '*.heic' does not exist
```

Single files converts fine.

**Comment by NeverMendel** [comment]
Hi @peekaa,

Thank you for raising this issue! The wildcard was not expanding correctly in Windows enviroments.

I've just addressed it and released a new version. I also added some tests to avoid regressions. Please, let me know should you face other issues
