### ISSUE TITLE
How about tweaking the argument order in README's Usage? 😊

### ISSUE THREAD

**Issue by acchanAlexander** [NeverMendel/heif-convert#27]
Hey there! 👋

First off, heif-convert is super useful—thank you for sharing it! 🙌

I was trying it out after reading the README’s Usage section, and I noticed something:

The command `heif-convert input.heic -f jpg` works perfectly, but when I tried `heif-convert *.heic -f jpg`, I ran into this error:

```
$ heif-convert *.heic -f jpg
usage: heif-convert [-h] [-o OUTPUT] [-p PATH]
                    [-f {jpg,png,webp,gif,tiff,bmp,ico}] [-q QUALITY] [-n] [-v]
                    [-vv] [-V]
                    input [input ...]
heif-convert: error: No matches found: *.heic
```

After some trial and error, I found that this command works just fine:
`heif-convert -f jpg *.heic`

I also noticed that the argument order in the Arguments section of the README aligns with this working version. Maybe the Usage section could reflect this order too for consistency? Just a thought! 😊

Thanks again for this awesome tool! 🚀

**Comment by acchanAlexander** [comment]
I'm running this on Windows 11 with WSL2, by the way! 😊

**Comment by NeverMendel** [comment]
Hi @acchanAlexander,

I'm happy to hear that you're finding `heif-convert` useful.

Thank you for taking the time to describe the issue you're facing. I tried reproducing it on my machine with WSL2 but I was not able to.

Would you mind running the following commands in the same folder as before and sharing the output here? Feel free to redact any sensitive information if necessary.

- `heif-convert --version`
- `ls *.heic`

**Comment by acchanAlexander** [comment]
Hey! Thanks for getting back to me! 😊

I just tried the command heif-convert `*.heic -f jpg` again, and it worked perfectly this time! 🎉

Looking back, I think I must’ve run it in a folder where there weren’t any files matching `*.heic`. Totally my mistake! 🙈

Sorry for the confusion!

Is it okay if I go ahead and close the pull request I made yesterday? Let me know! 👍

**Comment by NeverMendel** [comment]
Glad to hear it's working for you! I've simplified a little bit the README, and I'll go ahead and close your pull request as it's no longer needed.

If you encounter any other issues or have suggestions for improving heif-convert, feel free to let me know
